### ISSUE TITLE
Project package setup Needs to be restructured

### ISSUE THREAD

**Issue by wmarttala-cook** [wmarttala-cook/mydrive#29]
The package setup in the project is incorrect and it is causing the entire project to fail to be loaded correctly. Someone needs to refactor the package setup and get the project to run correctly.

**Comment by patrickdoane** [comment]
Changes made were as follows:
1.) We moved all packages to be subpackages of com.cooksys.mydrive.
2.) Pom.xml was changed to include the [mapstruct](http://mapstruct.org/) bean processor for maven compile-time.
3.) FolderEntity needed a publically namespaced constructor.
