### ISSUE TITLE
Post folder endpoint receives null is_deleted value in response DTO

### ISSUE THREAD

**Issue by emscook** [wmarttala-cook/mydrive#31]
called with empty database and body
"{
  "folder_id": 0,
  "is_deleted": false,
  "location": "haha",
  "name": "hoho"
}"
expected response:
"{
  "folder_id": 1,
  "location": "haha",
  "name": "hoho",
  "is_deleted": false
}"
received response:
"{
  "folder_id": null,
  "location": "haha",
  "name": "hoho",
  "is_deleted": null
}"

**Comment by patrickdoane** [comment]
Solved by commit 38522b250de139344c0aeaa51dad54d360cb525b
