### ISSUE TITLE
Implement Nav Component

### ISSUE THREAD

**Issue by patrickdoane** [wmarttala-cook/mydrive#44]
- [ ] Use [mui](https://material-ui.com/) components if necessary
- [ ] Create a [storybook](https://storybook.js.org/) story

Do this after we have all the sub-components (NavLink, NavButton, NavBrand) built.

**Comment by patrickdoane** [comment]
![navlink](https://user-images.githubusercontent.com/4065418/42647676-46fb916a-85ca-11e8-9917-56ce2c3c1641.jpg)

**Comment by wmarttala-cook** [comment]
Big fan of the screenshots you're adding
